# Generated by Django 6.1 on 2026-08-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('comida', 'Comida'), ('transporte', 'Transporte'), ('servicios', 'Servicios'), ('ropa', 'Ropa'), ('ocio', 'Ocio'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
